import './globals.css';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import Link from 'next/link';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Visx charts | Rechart.js',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={montserrat.className}>
        <main className='flex min-h-screen flex-col items-center p-24'>
          <h1 className='text-3xl font-bold mb-4'>Visx example charts</h1>

          <p>
            This are example of how to recreate rechart.js charts with visx{' '}
          </p>

          <Link href='/chart/lines'>Line chart</Link>
          {children}
        </main>
      </body>
    </html>
  );
}
